### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gpais311** [stLmpp/skill-mapping-api#1]
- [x] Languages
- [x] Description for skills
- [x] Description for skill level
- [x] Last update date
- [x] Last function (Tech lead, dev, manager, etc)
- [x] People lead EID
- [ ] Landing Page
